### ISSUE TITLE
Hapi v17 Support

### ISSUE THREAD

**Issue by timcosta** [captainjackrana/hapi-gate#2]
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [x] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [x] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [x] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.
* This issue is being opened because your plugin is listed on the official hapi website

**Comment by captainjackrana** [comment]
This module is being actively maintained. The new major version for Hapi support 17 will be released

**Comment by captainjackrana** [comment]
@timcosta can you refer me to an example of server instantiation with Hapiv17. Currently after linking hapiv17, my tests fail during server creation itself.
`/Users/iRana/hapi/lib/server.js:231
async inject(options) {
          ^^^^^^
SyntaxError: Unexpected identifier`

**Comment by timcosta** [comment]
@captainjackrana have you seen https://hapijs.com/api/17.0.0-rc9?

**Comment by captainjackrana** [comment]
@timcosta tried creating the hapi server using the v17 doc. Still getting the same error - 
```hapi/lib/server.js:231
    async inject(options) {
          ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iRana/hapi/lib/index.js:5:16)
    at Module._compile (module.js:541:32)```

**Comment by luminarious** [comment]
Any luck getting it to work?

**Comment by captainjackrana** [comment]
Upgraded to v2.0.0 with Hapi v17 support. Closing the ticket

**Comment by captainjackrana** [comment]
Upgraded to v2.0.0 with Hapi v17 support
