### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by andrevenancio** [captainjackrana/hapi-gate#7]
For anyone looking for a redirect from http to https or nonwww to www this seems to be the oficial tool.
However, the documentation on how to use isn't up to date to the newest hapi API.

You should call `plugin` not `register` and then pass the module with your options.
```javascript
server.register({
        plugin: require('hapi-gate'),
        options: { https: true, www: false },
    });
```

**Comment by captainjackrana** [comment]
Readme updated. Thanks for pointing it out..
